### ISSUE TITLE
Dropped character in parsing the README example

### ISSUE THREAD

**Issue by orivej** [Shinmera/plump-tex#6]
Just wanted to let you know that
`(plump:serialize (plump-tex:parse "Oh hey, \\how{are you} \\holding[up=there]{with all that} {exciting stuff} going on"))`
prints 
…`<holding up="there">ith all that</holding>`…
(missing `w` in `with`).

**Comment by Shinmera** [comment]
Oh my, how did I miss that. Thanks for reporting it!
